# This docker-compose file is woefully incomplete. The only reason why it is included is to give a quick recipe to deploy
# the application via docker/podman using the project's tooling and structure.
version: "3.7"
services:
  web:
    container_name: cuiloa
    build:
      context: ./
      dockerfile: "./apps/web/Containerfile"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: 'postgresql://penumbra:penumbra@postgres:5432/penumbra?sslmode=disable'
    depends_on:
      - postgres
  # The Postgres database, for storing CometBFT indexing info. 
  postgres:
    image: "docker.io/library/postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/postgres-cometbft-schema.sql:/docker-entrypoint-initdb.d/postgres-cometbft-schema.sql:ro
    environment:
      POSTGRES_PASSWORD: penumbra
      POSTGRES_USER: penumbra
      POSTGRES_DB: penumbra
    # depends_on:
    #   - pd-node0
volumes:
  cuiloa-app: {}
networks:
  cuiloa_network:
    external: true
